Repository RPSTD/component101, pull requests merged in 2023-02, with the labels that each got.

#11 Photoresistor sensor, RGB SMD Module
  PhotoresistorSensorLightSensor/IMG/a-picture-containing-text-electronics-circuit-d-2-768x445.png
  PhotoresistorSensorLightSensor/IMG/diagram-schematic-description-automatically-gene-2-768x448.png
  PhotoresistorSensorLightSensor/IMG/word-image-85.png
  PhotoresistorSensorLightSensor/IMG/word-image-89-768x388.png
  PhotoresistorSensorLightSensor/README.md
  RGBSMDModule/IMG/Arduino_KY-009_Keyes_RGB_LED_SMD_module_connection_diagram-1024x489.png
  RGBSMDModule/IMG/KY-009_Fritzing_custom_part_image-155x240.png
  RGBSMDModule/README.md
Labels: documentation, enhancement

#12 Momentry Button Module, Metal touch sensor
  MetalTouchSensor/IMG/ky-036-metal-touch-sensor-module.jpg
  MetalTouchSensor/IMG/ky036-metal-touch-sensor-module-sensitivity.jpg
  MetalTouchSensor/IMG/ky036-metal-touch-sensor-with-arduino-circuit-diagram-640x291 (1).jpg
  MetalTouchSensor/IMG/ky036-metal-touch-sensor-with-arduino-circuit-diagram-640x291.jpg
  MetalTouchSensor/IMG/pinout-of-the-ky036-metal-touch-sensor.jpg
  MetalTouchSensor/IMG/sawtooth-protection-with-metal-touch-sensor-640x336.jpg
  MetalTouchSensor/README.md
  MomentryButtonModule/IMG/arduino-compatible-push-button-sensor.jpg
  MomentryButtonModule/README.md
Labels: documentation, enhancement

#13 create README.md for component101
  README.md
Labels: documentation

#14 Update README.md
  README.md
Labels: bug, documentation

#15 GitHub Actions
  .github/workflows/blank.yml
  .github/workflows/checkreadme.yml
  .github/workflows/superlinter.yml
Labels: action

#16 Update superlinter.yml
  .github/workflows/superlinter.yml
Labels: bug, action

#19 Update checkreadme.yml
  .github/workflows/checkreadme.yml
Labels: bug, action

#17 Magnetic Reed Switch
  ElectromagneticFieldSensor/README.md
  GPSNEO6mModule/README.md
  MagneticReedSwitchModule/IMG/Arduino_KY-021_Keyes_mini_magnetic_reed_switch_module_connection_diagram-1024x527.png
  MagneticReedSwitchModule/IMG/ky-021_Fritzing_custom_part_image-178x240.png
  MagneticReedSwitchModule/README.md
Labels: documentation, enhancement

#20 Update superlinter.yml
  .github/workflows/superlinter.yml
Labels: enhancement, action

#21 Update superlinter.yml
  .github/workflows/superlinter.yml
Labels: bug, action

#22 CheckReadme file Updated
  .github/workflows/checkreadme.yml
  .github/workflows/superlinter.yml
Labels: bug, action

#23 Action and Readme Updated
  .github/workflows/checkreadme.yml
  ElectromagneticFieldSensor/README.md
  README.md
Labels: bug, enhancement, action

#24 Readme file Update
  .github/workflows/checkreadme.yml
  GSMmodule/README.md
  README.md
Labels: bug, documentation, enhancement

#25 Readme Update
  .github/workflows/checkreadme.yml
  HumiditySensor/README.md
  LightSensor/README.md
  README.md
Labels: bug, documentation, enhancement, action

#26 Logic Level Shifter
  .github/workflows/checkreadme.yml
  LogicLevelShifter/IMG/12009-06.jpg
  LogicLevelShifter/IMG/E0658944_level_shift_divider.png
  LogicLevelShifter/IMG/E0658944_level_shift_proper.png
  LogicLevelShifter/IMG/E0658944_level_shift_uart.png
  LogicLevelShifter/IMG/E0658944_level_shift_uart_basic.png
  LogicLevelShifter/IMG/spi-example_bb-02.png
  LogicLevelShifter/README.md
  README.md
Labels: documentation, enhancement

#27 Knock Sensor
  KnockSensor/IMG/Interfacing-Knock-Sensor-with-Arduino-Circuit-Diagram-768x617.jpg
  KnockSensor/IMG/Interfacing-Knock-Sensor-with-Arduino-Knock-Sensor-Internal-Circuit.jpg
  KnockSensor/IMG/Knock-Sensor-with-Arduino-Knock-Sensor-Pins.jpg
  KnockSensor/IMG/Knock-Sensor-with-Arduino-Knock-Sensor-Vibration-Sensor.jpg
  KnockSensor/README.md
  README.md
Labels: documentation, enhancement

#28 Update checkreadme.yml
  .github/workflows/checkreadme.yml
Labels: bug, action

#29 Update README.md
  .github/workflows/checkreadme.yml
  README.md
Labels: documentation, enhancement

#31 Update README.md
  .github/workflows/checkreadme.yml
  README.md
Labels: bug, documentation, enhancement, action

#32 Joystick Module
  JoystickModule/IMG/0_Joystick_with_Arduino_bb.png
  JoystickModule/IMG/Joy_diagram.jpeg
  JoystickModule/IMG/dsc09428.jpg
  JoystickModule/README.md
  KnockSensor/README.md
  LogicLevelShifter/README.md
  MagneticFeildSensor/README.md
  MetalTouchSensor/README.md
  MotionSensor/README.md
  PhotoresistorSensorLightSensor/README.md
  PressureSensor/README.md
  PulseSensor/README.md
  RGBSMDModule/README.md
  RotaryEncoderModule/README.md
  SoilMoistureSensor/README.md
  SoundSensor/README.md
  TemperatureSensor/README.md
  TiltSensor/README.md
  TrackingSensor/README.md
  TwoColorLEDModule/README.md
  VibrationSensor/README.md
  VibrationSensorArduino/README.md
  WaterLevelSensor/README.md
Labels: documentation, enhancement

#34 create Infrared Transmitter to component101
  InfraredTransmitter/IMG/Arduino-IR-Remote-Receiver-Breakout-Board-Wiring-Diagram-768x385.png
  InfraredTransmitter/IMG/Arduino-IR-Remote-Receiver-Tutorial-IR-Signal-Modulation-1024x276.png
  InfraredTransmitter/IMG/Arduino-IR-Remote-Receiver-Tutorial-NEC-Protocol-768x368.png
  InfraredTransmitter/IMG/Arduino-IR-Remote-Tutorial-IR-Receiver-Breakout-Board-610x570.jpg
  InfraredTransmitter/IMG/Arduino-IR-Remote-Tutorial-IR-Transmitter-LED-2-610x438.jpg
  InfraredTransmitter/IMG/Arduino-IR-Remote-Tutorial-Transmitting-LED-on-Remote-2-768x522.jpg
  InfraredTransmitter/IMG/Arduino-IR-Remote-Tutorial-Two-IR-Receiver-Diodes-768x749.jpg
  InfraredTransmitter/IMG/IR-Receiver-Breakout-Board-Pinout-Diagram-186x300.png
  InfraredTransmitter/IMG/IR-Receiver-Stand-Alone-Pinout-Diagram-157x300.png
  InfraredTransmitter/README.md
  README.md
Labels: documentation, enhancement

#36 create High voltage relay module to component101
  HighVoltageRelayModule/IMG/Arduino-Relay-Tutorial-with-Photoresistor-0001-Wirding-Diagram-1920x1113.jpg
  HighVoltageRelayModule/IMG/Arduino-Relay-Tutorial-with-Photoresistor-0002-Relay-Pinout-SRD-05VDC-SL-C.jpg
  HighVoltageRelayModule/IMG/normally-open-vs-normally-closed-the-geek-pub-relay.jpg
  HighVoltageRelayModule/README.md
  README.md
Labels: bug, documentation, enhancement

#37 create High Sensitivity Microphone Sensor
  HighSensitivityMicrophoneSensor/IMG/037-ARD.svg
  HighSensitivityMicrophoneSensor/IMG/400px-sens-poti-EN.png
  HighSensitivityMicrophoneSensor/IMG/KY-037.svg
  HighSensitivityMicrophoneSensor/IMG/arduino-compatible-ard2-audio-sensor-high-sensitivity.jpg
  HighSensitivityMicrophoneSensor/README.md
  README.md
Labels: documentation, enhancement

#38 Flame IR Sensor
  FlamemIRSensor/IMG/Circuit-Diagram-for-Flame-Sensor-Interfacing-with-Arduino.png
  FlamemIRSensor/IMG/Fire-or-flame-sensor-module.jpg
  FlamemIRSensor/README.md
  README.md
Labels: bug, documentation, enhancement

#39 Update README.md
  README.md
Labels: bug, documentation

#33 Create greetings.yml
  .github/workflows/greetings.yml
Labels: action

#40 Active piezo module,MKR 1000 Wi-Fi Module, Gas Sensor
  ActivePiezoBuzzerModule/IMG/Active-Buzzer-610x721.png
  ActivePiezoBuzzerModule/IMG/Active-Buzzer-vs-Passive-Buzzer-768x298.jpg
  ActivePiezoBuzzerModule/IMG/How-to-Setup-Active-and-Passive-Buzzers-on-an-Arduino-How-Buzzers-Work-768x324.png
  ActivePiezoBuzzerModule/README.md
  GasSensor/IMG/Arduino-Wiring-MQ2-Gas-Sensor-Analog-Output.png
  GasSensor/IMG/Inside-Gas-Sensor-Internal-Structure-with-Sensing-Element-Connecting-Legs.jpg
  GasSensor/IMG/MQ2-Gas-Sensor-Internal-Structure-Sensing-Element.png
  GasSensor/IMG/MQ2-Gas-Sensor-Module-Pinout.png
  GasSensor/IMG/MQ2-Gas-Sensor-Module.jpg
  GasSensor/IMG/MQ2-Gas-Sensor-Output.gif
  GasSensor/IMG/MQ2-Gas-Sensor-Parts-Hardware-Overview.jpg
  GasSensor/IMG/MQ2-Gas-Sensor-Working.gif
  GasSensor/IMG/MQ2-Gas-Sensor.jpg
  GasSensor/IMG/MQ2-Sensor-LM393-Comparator-with-Sensitivity-Adjustment-pot.jpg
  GasSensor/IMG/MQ2-Sensor-Power-and-Status-LEDs.jpg
  GasSensor/IMG/Sensing-Element-Aluminium-Oxide-Ceramic-with-Tin-Dioxide-Coating.jpg
  GasSensor/README.md
  MKR1000WifiModule/IMG/MKR1000_T1_IMG01.png
  MKR1000WifiModule/README.md
  MOSFETDriveModule/IMG/IRF520-MOSFET-Driver-Circuit-1.jpg
  MOSFETDriveModule/IMG/IRF520-MOSFET-Driver-Module.jpg
  MOSFETDriveModule/IMG/IRF520-MOSFET-Driver-Pinout.jpg
  MOSFETDriveModule/README.md
  README.md
Labels: bug, documentation, enhancement
