Repository RPSTD/component101, pull requests merged in 2023-03, with the labels that each got.

#41 create touch sensor to component101
  README.md
  TouchSensorModule/IMG/Touch-sensor-with-Arduino-connection-diagram.jpg
  TouchSensorModule/IMG/Touch-sensor-with-Arduino-hardware.jpg
  TouchSensorModule/IMG/Touch-sensor.jpg
  TouchSensorModule/README.md
Labels: documentation, enhancement

#42 Keypad Arduino
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-3X4-and-4X4-Keypads-610x703.jpg
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-4X4-Keypad-Schematic-610x494.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-4X4-and-3X4-Keypad-Connection-Diagram-768x772.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-4X4-and-3X4-Keypad-Pin-Diagram-610x580.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-How-the-Keypad-Works-STEP-1-296x300.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-How-the-Keypad-Works-STEP-2-296x300.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-How-the-Keypad-Works-STEP-3-296x300.png
  KeypadArduino/IMG/Arduino-Keypad-Tutorial-How-the-Keypad-Works-STEP-4-296x300.png
  KeypadArduino/IMG/How-to-Set-Up-a-Keypad-on-an-Arduino-Back-Side-of-Keypad-610x718.jpg
  KeypadArduino/README.md
  README.md
Labels: documentation, enhancement

#43 Breadboard Power Supply Module
  BreadboardPowerSupplyModule/IMG/MB102-Breadboard-Power-Supply-Module.jpg
  BreadboardPowerSupplyModule/IMG/download.jpeg
  BreadboardPowerSupplyModule/README.md
  KeypadArduino/README.md
  README.md
Labels: bug, documentation, enhancement

#44 pH sensor
  PHSensor/IMG/How_to_measure_the_pH_with_a_microcontroller_480x480.png
  PHSensor/IMG/What_is_a_pH_sensor_480x480.png
  PHSensor/IMG/ph_scale_480x480.jpg
  PHSensor/IMG/ph_sensor_diagram_480x480.png
  PHSensor/IMG/ph_sensor_working_principle_480x480.png
  PHSensor/README.md
  README.md
Labels: documentation, enhancement

#45 Reed switch module,Laser Module, Gravity Sensor,Position Sensor,Liquid Crystal Sensor,Fingerprint Sensor
  FingerPrintSensor/IMG/AS608-Fingerprint-Circuit-.jpg
  FingerPrintSensor/IMG/AS608-Fingerprint-Module.jpg
  FingerPrintSensor/IMG/AS608-Fingerprint-Pinout.jpg
  FingerPrintSensor/README.md
  GravitySensor/IMG/download.png
  GravitySensor/IMG/gravity_sensor.jpeg
  GravitySensor/README.md
  LaserModule/IMG/Arduino_KY-008_Keyes_Laser_transmitter_module_connection_diagram-1024x522.png
  LaserModule/IMG/KY-008_laser_transmitter_arduino_module-240x240.png
  LaserModule/README.md
  LiquidCrystalSensor/IMG/LCD-Display-Tutorial.png
  LiquidCrystalSensor/IMG/LCD-Display_Transparent03.png
  LiquidCrystalSensor/IMG/What-is-LCD-Character-Display-Arduino-LCD-Tutorial-768x498.png
  LiquidCrystalSensor/README.md
  PositionSensor/IMG/Position_Sensor.jpg
  PositionSensor/IMG/Sensor.jpeg
  PositionSensor/IMG/download (1).jpeg
  PositionSensor/IMG/download.jpeg
  PositionSensor/README.md
  QRReader/IMG/Arduino-QR-Code-Scanner-640x290.jpg
  QRReader/IMG/Barcode.jpg
  QRReader/IMG/Maikrt-Embedded-QR-Code-Barcode-Scanning-Module.jpg
  QRReader/IMG/Pinout-640x290.jpg
  QRReader/IMG/QR-Code-Details-640x330 (1).jpg
  QRReader/IMG/QR-Code-Details-640x330.jpg
  QRReader/IMG/QR-Codes-640x360.jpg
  QRReader/IMG/barcodestripes.gif
  QRReader/IMG/how-barcode-scanner-works.png
  QRReader/README.md
  README.md
  ReedSwitchModule/IMG/Arduino_KY-025_Keyes_Reed_Switch_module_connection_diagram-1024x662.webp
  ReedSwitchModule/IMG/Mini-Reed-Switch-Module.jpg
  ReedSwitchModule/IMG/Reed-Switch-Module-Schematic-2.jpg
  ReedSwitchModule/README.md
Labels: documentation, enhancement

#46 Accelerometer and Gyroscope Module, Rain Sensor
  AccelerometerAndGyroscopeSensor/IMG/Accelerometer-Working-Illustration-Gravitation-Force.jpg
  AccelerometerAndGyroscopeSensor/IMG/Accelerometer-Working-Illustration-Sudden-Movement.jpg
  AccelerometerAndGyroscopeSensor/IMG/Accelerometer-Working-Illustration-Weightless-State.jpg
  AccelerometerAndGyroscopeSensor/IMG/Coriolis-Force-On-Two-Masses.png
  AccelerometerAndGyroscopeSensor/IMG/Coriolis-Force-On-a-Mass.png
  AccelerometerAndGyroscopeSensor/IMG/Decaped-L3GD20HTR-MEMS-Gyroscope.jpg
  AccelerometerAndGyroscopeSensor/IMG/MEMS-Accelerometer-Working.gif
  AccelerometerAndGyroscopeSensor/IMG/MPU6050-3-axis-Accelerometer-Gyroscope-Module-Pinout.png
  AccelerometerAndGyroscopeSensor/IMG/MPU6050-Accel-Gyro-Working-Drive-Mode-Output.gif
  AccelerometerAndGyroscopeSensor/IMG/MPU6050-Accel-Gyro-Working-Pitch-Mode-Output.gif
  AccelerometerAndGyroscopeSensor/IMG/MPU6050-Accel-Gyro-Working-Roll-Mode-Output.gif
  AccelerometerAndGyroscopeSensor/IMG/MPU6050-Accel-Gyro-Working-Yaw-Mode-Output.gif
  AccelerometerAndGyroscopeSensor/IMG/Wiring-MPU6050-Accel-Gyro-Module-with-Arduino.png
  AccelerometerAndGyroscopeSensor/README.md
  README.md
  RainSensor/IMG/Interfacing-Rain-Sensor-with-Arduino-Circuit-Diagram.png
  RainSensor/IMG/Rain-Control-Module.png
  RainSensor/IMG/Rain-Sensor.png
  RainSensor/README.md
Labels: documentation, enhancement

#47 Load Cell Sensor
  LoadCellSensor/IMG/interfacing-hx711-with-arduino-weight-scale-circuit-diagram-1.png
  LoadCellSensor/IMG/load-cell-attachment-with-base-to-create-weighting-platform.png
  LoadCellSensor/IMG/wheatstone-bridge-for-strain-guage-load-cell.png
  LoadCellSensor/README.md
  README.md
Labels: documentation, enhancement

#50 Update LICENSE
  FingerPrintSensor/IMG/finalPic.png
  FingerPrintSensor/README.md
  LICENSE
Labels: bug, documentation

#51 4 add a format to the readme file
  GPSNEO6mModule/IMG/UpdatePIC.png
  GPSNEO6mModule/README.md
Labels: bug, documentation, enhancement

#55 4 add a format to the readme file
  MagneticReedSwitchModule/IMG/Arduino_KY-021_Keyes_mini_magnetic_reed_switch_module_connection_diagram-1024x527.png
  MagneticReedSwitchModule/IMG/IMG.png
  MagneticReedSwitchModule/IMG/ky-021_Fritzing_custom_part_image-178x240.png
  MagneticReedSwitchModule/README.md
  MomentryButtonModule/IMG/IMG.png
  MomentryButtonModule/IMG/arduino-compatible-push-button-sensor.jpg
  MomentryButtonModule/README.md
  README.md
  RGBSMDModule/IMG/Arduino_KY-009_Keyes_RGB_LED_SMD_module_connection_diagram-1024x489.png
  RGBSMDModule/IMG/IMG.png
  RGBSMDModule/IMG/KY-009_Fritzing_custom_part_image-155x240.png
  RGBSMDModule/README.md
  TiltSensor/IMG/43-300x130.jpg
  TiltSensor/IMG/FSNZGEKFWS6K6V5.png
  TiltSensor/IMG/FW0A0QBFWS6K6V4.png
  TiltSensor/IMG/IMG.png
  TiltSensor/IMG/tilt.png
  TiltSensor/README.md
Labels: bug, documentation, enhancement

#58 Motion Sensor
  MotionSensor/mortion_sensor/mortion_sensor.ino
  README.md
Labels: enhancement

#61 create code file
  GravitySensor/gravity_sensor/gravity_sensor.ino
  HumiditySensor/humidity_sensor/humidity_sensor.ino
  MoistureSensor/moisture_sensor/moisture_sensor.ino
  TemperatureSensor/temperature_sensor/temperature_sensor.ino
Labels: enhancement

#59 Dev
  GravitySensor/gravity_sensor/gravity_sensor.ino
  HumiditySensor/humidity_sensor/humidity_sensor.ino
  MoistureSensor/moisture_sensor/moisture_sensor.ino
  MotionSensor/mortion_sensor/mortion_sensor.ino
  README.md
  TemperatureSensor/temperature_sensor/temperature_sensor.ino
Labels: enhancement

#62 Vibration Sensor
  PressureSensor/pressure_sensor/pressure_sensor.ino
  VibrationSensorArduino/vibration_sensor/vibration_sensor.ino
Labels: enhancement

#65 Create electro_magnetic_field_sensor.ino
  ElectromagneticFieldSensor/electro_magnetic_field_senosor/electro_magnetic_field_sensor.ino
Labels: enhancement

#67 Position Sensor
  PositionSensor/position_sensor/position_sensor.ino
  SoundSensor/sound_sensor/sound_sensor.ino
Labels: enhancement

#68 Create .github/workflows/codeql.yml
  .github/workflows/codeql.yml
Labels: action

#69 Water Level Sensor, Ultrasonic Distance Sensor, Two Color LED Module, Tracking Sensor
  .github/workflows/codeql.yml
  TrackingSensor/tracking_sensor/tracking_sensor.ino
  TwoColorLEDModule/two_color_LED_module/two_color_LED_module.ino
  UltrasonicDistanceSensor/ultrasonic_distance_sensor/ultrasonic_distance_sensor.ino
  WaterLevelSensor/water_level_sensor/water_level_senor.ino
Labels: enhancement

#71 Tilt Sensor,GPS_NEO_6m module, Rotary Encoder module, RGB_SMD module
  GPSNEO6mModule/gps_neo_6m_module/gps_neo_6m_module.ino
  RGBSMDModule/rgb_smd_module/rgb_smd_module.ino
  RotaryEncoderModule/rotory_encoder_module/rotary_encoder_module.ino
  TiltSensor/tilt_sensor/tilt_sensor.ino
  TrackingSensor/tracking_sensor/tracking_sensor.ino
Labels: enhancement

#66 Dev
  .github/workflows/codeql.yml
  ElectromagneticFieldSensor/electro_magnetic_field_senosor/electro_magnetic_field_sensor.ino
  GPSNEO6mModule/gps_neo_6m_module/gps_neo_6m_module.ino
  PositionSensor/README.md
  PositionSensor/position_sensor/position_sensor.ino
  PressureSensor/pressure_sensor/pressure_sensor.ino
  README.md
  RGBSMDModule/rgb_smd_module/rgb_smd_module.ino
  RotaryEncoderModule/rotory_encoder_module/rotary_encoder_module.ino
  SoundSensor/sound_sensor/sound_sensor.ino
  TiltSensor/tilt_sensor/tilt_sensor.ino
  TrackingSensor/tracking_sensor/tracking_sensor.ino
  TwoColorLEDModule/two_color_LED_module/two_color_LED_module.ino
  UltrasonicDistanceSensor/ultrasonic_distance_sensor/ultrasonic_distance_sensor.ino
  VibrationSensorArduino/vibration_sensor/vibration_sensor.ino
  WaterLevelSensor/water_level_sensor/water_level_senor.ino
Labels: documentation, enhancement

#73 Magnetic Read Switch Module, Metal Touch Sensor, Photo Resistor Sensor, Momentary Button Module
  MagneticReedSwitchModule/magnetic_read_switch/magnetic_read_switch.ino
  MetalTouchSensor/metal_touch_sensor/metal_touch_sensor.ino
  MomentryButtonModule/momentry_button_sensor/momentry_button_sensor.ino
  PhotoresistorSensorLightSensor/photoresistor_sensor/photoresister_sensor.ino
Labels: enhancement

#74 Logic level Shifter, Knock Sensor, Joystick Sensor, Infrared Transmitter
  InfraredTransmitter/infrared_transmitter/infrared_transmitter.ino
  JoystickModule/joystick_module/joystick_module.ino
  KnockSensor/knock_sensor/knock_sensor.ino
  LogicLevelShifter/logic_level_shifter/logic_level_shifter.ino
Labels: enhancement

#75 Load Cell Sensor, High Voltage Relay Module, High Sensitivity Microphone, Pulse Sensor
  HighSensitivityMicrophoneSensor/high_sensitivity_microphone_sensor/high_sensitivity_microphone_sensor.ino
  HighVoltageRelayModule/high_voltage_relay_module/high_voltage_relay_module.ino
  LoadCellSensor/load_cell_sensor/load_cell_sensor.ino
  PulseSensor/pulse_sensor/pulse_sensor.ino
Labels: enhancement

#76 Dev
  HighSensitivityMicrophoneSensor/high_sensitivity_microphone_sensor/high_sensitivity_microphone_sensor.ino
  HighVoltageRelayModule/high_voltage_relay_module/high_voltage_relay_module.ino
  InfraredTransmitter/infrared_transmitter/infrared_transmitter.ino
  JoystickModule/joystick_module/joystick_module.ino
  KnockSensor/knock_sensor/knock_sensor.ino
  LoadCellSensor/load_cell_sensor/load_cell_sensor.ino
  LogicLevelShifter/logic_level_shifter/logic_level_shifter.ino
  MKR1000WifiModule/MKR_1000_WI-Fi _module/MKR_1000_WI-Fi _module.ino
  MagneticReedSwitchModule/magnetic_read_switch/magnetic_read_switch.ino
  MetalTouchSensor/metal_touch_sensor/metal_touch_sensor.ino
  MomentryButtonModule/momentry_button_sensor/momentry_button_sensor.ino
  PhotoresistorSensorLightSensor/photoresistor_sensor/photoresister_sensor.ino
  PulseSensor/pulse_sensor/pulse_sensor.ino
Labels: enhancement
